services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - OCR_SERVICE_URL=http://ocr-service:4000
    depends_on:
      - postgres_db
      - ocr-service
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/ocr-service
      - ./scoring-frontend:/app/scoring-frontend

  api-simulacion:
    build: ./api-simulacion
    ports:
      - "4000:3000"
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000

  frontend:
    build:
      context: ./frontend-banco
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-banco:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_API_SIMULACION_URL=http://api-simulacion:3000/api/v1
    depends_on:
      - app
      - api-simulacion

  ocr-service:
    build:
      context: ./ocr-service
    ports:
      - "4500:4000" # ‚Üê NUEVO PUERTO
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    volumes:
      - ./key.json:/app/key.json

  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
