version: "3.8"
services:
  # --- SERVICIO ELIMINADO TEMPORALMENTE (CAUSABA EL ERROR) ---
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres_db
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules

  # --- TU API REAL ---
  api-simulacion:
    build: ./api-simulacion 
    ports:
      - "4000:3000"  
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres_db  
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - postgres_db

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend-banco
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-banco:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_API_SIMULACION_URL=http://localhost:4000/api/v1 
    depends_on:
      # - app 
      - api-simulacion

  # --- BASE DE DATOS ---
  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: